services:
  - type: web
    name: kits-electromenager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATABASE_URL
        fromDatabase:
          name: kits_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: kits_db
    databaseName: kits_db
    user: kits_db_user
    plan: free 