"""Initial migration

Revision ID: 75a47bda3578
Revises: 
Create Date: 2025-02-27 15:58:28.278035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a47bda3578'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kit_produits', schema=None) as batch_op:
        batch_op.drop_column('quantite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kit_produits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantite', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
